-- version from 2026-06-17 RS

DROP SCHEMA IF EXISTS gras CASCADE;
CREATE DATABASE gras;

CREATE USER gras_user WITH PASSWORD 'gras_password';
GRANT ALL PRIVILEGES ON DATABASE gras TO gras_user;

\c gras;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE domain (
    name varchar(255) PRIMARY KEY,
    description varchar(255) NOT NULL DEFAULT ''
);
ALTER TABLE domain OWNER TO gras_user;

CREATE TABLE project (
    name varchar(255) PRIMARY KEY,
    description varchar(255) NOT NULL DEFAULT ''
);
ALTER TABLE project OWNER TO gras_user;

CREATE TABLE "user" (
    name varchar(255) PRIMARY KEY,
    password varchar(255),
    active boolean DEFAULT true,
    description varchar(255) NOT NULL DEFAULT '',
    email varchar(255) NOT NULL DEFAULT ''
);
ALTER TABLE "user" OWNER TO gras_user;

CREATE TABLE role (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) UNIQUE NOT NULL,
    project_name varchar(255) NOT NULL REFERENCES project(name),
    description varchar(255) NOT NULL DEFAULT ''
);
ALTER TABLE role OWNER TO gras_user;

CREATE TABLE group_ (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    project_name varchar(255) NOT NULL REFERENCES project(name),
    description varchar(255) NOT NULL DEFAULT '',
    CONSTRAINT unique_name_project UNIQUE(name, project_name)
);
ALTER TABLE group_ OWNER TO gras_user;

CREATE TABLE group_role_mapping (
    group_id integer NOT NULL REFERENCES group_(id) ON DELETE CASCADE,
    role_id integer NOT NULL REFERENCES role(id),
    PRIMARY KEY(group_id, role_id)
);
ALTER TABLE group_role_mapping OWNER TO gras_user;

CREATE TABLE permission (
    group_id integer NOT NULL REFERENCES group_(id),
    user_name varchar(255) NOT NULL REFERENCES "user"(name),
    domain_name varchar(255) NOT NULL REFERENCES domain(name),
    PRIMARY KEY(group_id,user_name,domain_name)
);
ALTER TABLE permission OWNER TO gras_user;

CREATE TABLE hist_domain (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    description varchar(255) NOT NULL,
    ts timestamp NOT NULL,
    action varchar(255) NOT NULL
);
ALTER TABLE hist_domain OWNER TO gras_user;

CREATE TABLE hist_project (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    description varchar(255) NOT NULL,
    ts timestamp NOT NULL,
    action varchar(255) NOT NULL
);
ALTER TABLE hist_project OWNER TO gras_user;

CREATE TABLE hist_user (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    password varchar(255),
    active boolean,
    description varchar(255),
    email varchar(255),
    ts timestamp NOT NULL,
    action varchar(255) NOT NULL
);
ALTER TABLE hist_user OWNER TO gras_user;

CREATE TABLE hist_role (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id integer NOT NULL,
    name varchar(255) NOT NULL,
    project_name varchar(255) NOT NULL,
    description varchar(255) NOT NULL,
    ts timestamp NOT NULL,
    action varchar(255) NOT NULL
);
ALTER TABLE hist_role OWNER TO gras_user;

CREATE TABLE hist_group_ (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id integer NOT NULL,
    name varchar(255) NOT NULL,
    project_name varchar(255) NOT NULL,
    description varchar(255) NOT NULL,
    ts timestamp NOT NULL,
    action varchar(255) NOT NULL
);
ALTER TABLE hist_group_ OWNER TO gras_user;

CREATE TABLE hist_group_role_mapping (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id varchar(255) NOT NULL,
    role_id varchar(255) NOT NULL,
    ts timestamp NOT NULL,
    action varchar(255) NOT NULL
);
ALTER TABLE hist_group_role_mapping OWNER TO gras_user;

CREATE TABLE hist_permission (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id integer NOT NULL,
    user_name varchar(255) NOT NULL,
    domain_name varchar(255) NOT NULL,
    ts timestamp NOT NULL,
    action varchar(255) NOT NULL
);
ALTER TABLE hist_permission OWNER TO gras_user;

CREATE OR REPLACE VIEW domainuser_password AS
SELECT DISTINCT concat_ws('@',p.user_name,p.domain_name) AS domainuser,  u.password
FROM permission p
JOIN "user" u ON u.name=p.user_name
WHERE u.active=true;
ALTER VIEW domainuser_password OWNER TO gras_user;

CREATE OR REPLACE VIEW domainuser_role AS
SELECT DISTINCT concat_ws('@',p.user_name,p.domain_name) AS domainuser, r.name AS role
FROM permission p
JOIN group_role_mapping m ON p.group_id=m.group_id
JOIN role r ON m.role_id=r.id
JOIN "user" u ON u.name=p.user_name
WHERE u.active=true;
ALTER VIEW domainuser_role OWNER TO gras_user;

CREATE OR REPLACE VIEW validate AS
SELECT DISTINCT a.domainuser,a.password,b.role
FROM domainuser_password a
JOIN domainuser_role b USING(domainuser);
ALTER VIEW validate OWNER TO gras_user;

CREATE OR REPLACE PROCEDURE createDomain(domainName varchar, description varchar)
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO domain(name,description)
    VALUES(domainName,description)
    ON CONFLICT(name) DO NOTHING;
END $$;
ALTER PROCEDURE createDomain(domainName varchar, description varchar) OWNER TO gras_user;

CREATE OR REPLACE PROCEDURE createProject(projectName varchar, description varchar)
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO project(name,description)
    VALUES(projectName,description)
    ON CONFLICT(name) DO NOTHING;
END $$;
ALTER PROCEDURE createProject(projectName varchar, description varchar) OWNER TO gras_user;

CREATE OR REPLACE PROCEDURE createUser(userName varchar, passwd varchar, description varchar)
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO "user"(name,password,active,description)
    VALUES(userName, encode(digest(passwd,'sha256'),'hex'), true, description)
    ON CONFLICT(name) DO NOTHING;
END $$;
ALTER PROCEDURE createUser(userName varchar, passwd varchar, description varchar) OWNER TO gras_user;

CREATE OR REPLACE PROCEDURE createGroup(projectName varchar, groupName varchar, description varchar)
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO group_(name,project_name,description)
    VALUES(groupName,projectName,description);
END $$;
ALTER PROCEDURE createGroup(projectName varchar, groupName varchar, description varchar) OWNER TO gras_user;

CREATE OR REPLACE PROCEDURE createRole(projectName varchar, roleName varchar, description varchar)
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO role(name,project_name,description)
    VALUES(roleName,projectName,description);
END $$;
ALTER PROCEDURE createRole(projectName varchar, roleName varchar, description varchar) OWNER TO gras_user;

CREATE OR REPLACE PROCEDURE createGroupRoleMapping(projectName varchar, groupName varchar, roleName varchar)
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO group_role_mapping(group_id,role_id)
    SELECT g.id,r.id
    FROM group_ g
             JOIN role r ON r.name=roleName
    WHERE g.name=groupName AND g.project_name=projectName;
END $$;
ALTER PROCEDURE createGroupRoleMapping(projectName varchar, groupName varchar, roleName varchar) OWNER TO gras_user;

CREATE OR REPLACE PROCEDURE grantAdminRights(domainName varchar, projectName varchar, userName varchar)
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO permission(group_id,user_name,domain_name)
    SELECT id,userName,domainName
    FROM group_
    WHERE project_name=projectName
    ON CONFLICT DO NOTHING;
END $$;
ALTER PROCEDURE grantAdminRights(domainName varchar, projectName varchar, userName varchar) OWNER TO gras_user;

CREATE OR REPLACE PROCEDURE grantStandardRights(domainName varchar, projectName varchar, userName varchar)
LANGUAGE plpgsql AS $$
BEGIN
    DELETE FROM permission p
        USING group_ g
    WHERE p.group_id=g.id
      AND p.user_name=userName
      AND p.domain_name=domainName
      AND g.project_name=projectName;

    INSERT INTO permission(group_id,user_name,domain_name)
    SELECT id,userName,domainName
    FROM group_
    WHERE project_name=projectName
      AND name !~* 'admin'
    ON CONFLICT DO NOTHING;
END $$;
ALTER PROCEDURE grantStandardRights(domainName varchar, projectName varchar, userName varchar) OWNER TO gras_user;
