DROP SCHEMA IF EXISTS notification_service CASCADE;
CREATE DATABASE notification_service ENCODING 'UTF8';

CREATE USER noti_user WITH PASSWORD 'noti_password';
GRANT ALL PRIVILEGES ON DATABASE notification_service TO noti_user;

\c notification_service;

CREATE TABLE configuration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activated BOOLEAN,
    configKey VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    value TEXT
);
ALTER TABLE configuration OWNER TO noti_user;

INSERT INTO configuration (
    id,
    activated,
    configKey,
    description,
    value
) VALUES (
    1,
    TRUE,
    'notification.config',
    NULL,
    '<org.emau.icmvc.ttp.notification.service.model.config.NotificationConfig>
    <consumerConfigs>
        <param>
            <key>Dispatcher</key>
            <value class="org.emau.icmvc.ttp.notification.service.model.config.ConsumerConfig">
                <connectionType>EJB</connectionType>
                <messageTypes>
                    <string>EPIX.AssignIdentity</string>
                </messageTypes>
                <excludeClientIdFilter class="set">
                    <string>gICS_Web</string>
                </excludeClientIdFilter>
                <parameter>
                    <param>
                        <key>ejb.jndi.url</key>
                        <value>java:global/test-dispatcher-ear-1.15.3/dispatcher-services-1.15.3/InternalNotificationConsumer</value>
                    </param>
                </parameter>
            </value>
        </param>
        <param>
            <key>HTTPConsumer</key>
            <value class="org.emau.icmvc.ttp.notification.service.model.config.ConsumerConfig">
                <connectionType>HTTP</connectionType>
                <messageTypes>
                    <string>GICS.exampleMethodWithNotification</string>
                </messageTypes>
                <excludeClientIdFilter class="set">
                    <string>E-PIX_Web</string>
                </excludeClientIdFilter>
                <parameter>
                    <param>
                        <key>url</key>
                        <value>https://httpbin.org/post</value>
                    </param>
                    <param>
                        <key>username</key>
                        <value>pp</value>
                    </param>
                    <param>
                        <key>passwort</key>
                        <value>pwd</value>
                    </param>
                </parameter>
            </value>
        </param>
    </consumerConfigs>
</org.emau.icmvc.ttp.notification.service.model.config.NotificationConfig>'
);

SELECT setval(
    pg_get_serial_sequence('configuration', 'id'),
    (SELECT MAX(id) FROM configuration)
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id VARCHAR(255) NOT NULL,
    consumer_id VARCHAR(255) NOT NULL,
    creationDate TIMESTAMP NOT NULL,
    data TEXT NOT NULL,
    send_date TIMESTAMP,
    status VARCHAR(255),
    type VARCHAR(255) NOT NULL,
    error_message TEXT
);
ALTER TABLE notifications OWNER TO noti_user;

CREATE TABLE sequence (
    seq_name VARCHAR(50) PRIMARY KEY,
    seq_count NUMERIC(38,0)
);
ALTER TABLE sequence OWNER TO noti_user;

INSERT INTO sequence (seq_name, seq_count)
VALUES ('SEQ_GEN', 0);
