name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.14"
          - "3.13"
          - "3.12"
          - "3.11"
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - name: Set up Poetry
        uses: ./.github/actions/setup-poetry
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: poetry install --with dev
      - name: Test
        run: poetry run pytest tests --cov=fable_client --cov-branch --cov-fail-under=90
        env:
          PYTEST_USE_TESTCONTAINERS: 1
